language: node_js

node_js:
  - 0.12

before_script:
  - npm install grunt-cli -g

script:
  - grunt test-travis --verbose
  - grunt karma:saucelabs --force --verbose

notifications:
  email:
    on_success: never

addons:
  sauce_connect: true
